// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: cosmos/crypto/secp256k1/keys.proto

// Trimmed, wire-compatible subset of cosmos/crypto/secp256k1/keys.proto.

package secp256k1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PubKey is a compressed (33-byte) secp256k1 public key.
// Type URL: /cosmos.crypto.secp256k1.PubKey.
type PubKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubKey) Reset() {
	*x = PubKey{}
	mi := &file_cosmos_crypto_secp256k1_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKey) ProtoMessage() {}

func (x *PubKey) ProtoReflect() protoreflect.Message {
	mi := &file_cosmos_crypto_secp256k1_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKey.ProtoReflect.Descriptor instead.
func (*PubKey) Descriptor() ([]byte, []int) {
	return file_cosmos_crypto_secp256k1_keys_proto_rawDescGZIP(), []int{0}
}

func (x *PubKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_cosmos_crypto_secp256k1_keys_proto protoreflect.FileDescriptor

var file_cosmos_crypto_secp256k1_keys_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f,
	0x73, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36, 0x6b, 0x31, 0x22, 0x1a, 0x0a,
	0x06, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x73, 0x75, 0x6b, 0x65, 0x59,
	0x6f, 0x64, 0x61, 0x2f, 0x67, 0x6f, 0x64, 0x65, 0x78, 0x2f, 0x64, 0x79, 0x64, 0x78, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x63, 0x70, 0x32, 0x35, 0x36,
	0x6b, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cosmos_crypto_secp256k1_keys_proto_rawDescOnce sync.Once
	file_cosmos_crypto_secp256k1_keys_proto_rawDescData []byte
)

func file_cosmos_crypto_secp256k1_keys_proto_rawDescGZIP() []byte {
	file_cosmos_crypto_secp256k1_keys_proto_rawDescOnce.Do(func() {
		file_cosmos_crypto_secp256k1_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosmos_crypto_secp256k1_keys_proto_rawDesc), len(file_cosmos_crypto_secp256k1_keys_proto_rawDesc)))
	})
	return file_cosmos_crypto_secp256k1_keys_proto_rawDescData
}

var file_cosmos_crypto_secp256k1_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cosmos_crypto_secp256k1_keys_proto_goTypes = []any{
	(*PubKey)(nil), // 0: cosmos.crypto.secp256k1.PubKey
}
var file_cosmos_crypto_secp256k1_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_crypto_secp256k1_keys_proto_init() }
func file_cosmos_crypto_secp256k1_keys_proto_init() {
	if File_cosmos_crypto_secp256k1_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosmos_crypto_secp256k1_keys_proto_rawDesc), len(file_cosmos_crypto_secp256k1_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_crypto_secp256k1_keys_proto_goTypes,
		DependencyIndexes: file_cosmos_crypto_secp256k1_keys_proto_depIdxs,
		MessageInfos:      file_cosmos_crypto_secp256k1_keys_proto_msgTypes,
	}.Build()
	File_cosmos_crypto_secp256k1_keys_proto = out.File
	file_cosmos_crypto_secp256k1_keys_proto_goTypes = nil
	file_cosmos_crypto_secp256k1_keys_proto_depIdxs = nil
}
