// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: dydxprotocol/accountplus/tx.proto

// Trimmed, wire-compatible subset of dydxprotocol/accountplus/tx.proto. godex
// only needs TxExtension, which names the on-chain authenticators that
// authorize a transaction signed by a scoped trading key. Registering those
// authenticators (MsgAddAuthenticator) is deliberately out of scope.

package accountplus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxExtension rides in TxBody.non_critical_extension_options.
// Type URL: /dydxprotocol.accountplus.TxExtension.
type TxExtension struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SelectedAuthenticators []uint64               `protobuf:"varint,1,rep,packed,name=selected_authenticators,json=selectedAuthenticators,proto3" json:"selected_authenticators,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TxExtension) Reset() {
	*x = TxExtension{}
	mi := &file_dydxprotocol_accountplus_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxExtension) ProtoMessage() {}

func (x *TxExtension) ProtoReflect() protoreflect.Message {
	mi := &file_dydxprotocol_accountplus_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxExtension.ProtoReflect.Descriptor instead.
func (*TxExtension) Descriptor() ([]byte, []int) {
	return file_dydxprotocol_accountplus_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxExtension) GetSelectedAuthenticators() []uint64 {
	if x != nil {
		return x.SelectedAuthenticators
	}
	return nil
}

var File_dydxprotocol_accountplus_tx_proto protoreflect.FileDescriptor

var file_dydxprotocol_accountplus_tx_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6c, 0x75, 0x73, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x18, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6c, 0x75, 0x73, 0x22, 0x46, 0x0a,
	0x0b, 0x54, 0x78, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x17,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x16, 0x73,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x73, 0x75, 0x6b, 0x65, 0x59, 0x6f, 0x64, 0x61, 0x2f,
	0x67, 0x6f, 0x64, 0x65, 0x78, 0x2f, 0x64, 0x79, 0x64, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6c, 0x75, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_dydxprotocol_accountplus_tx_proto_rawDescOnce sync.Once
	file_dydxprotocol_accountplus_tx_proto_rawDescData []byte
)

func file_dydxprotocol_accountplus_tx_proto_rawDescGZIP() []byte {
	file_dydxprotocol_accountplus_tx_proto_rawDescOnce.Do(func() {
		file_dydxprotocol_accountplus_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dydxprotocol_accountplus_tx_proto_rawDesc), len(file_dydxprotocol_accountplus_tx_proto_rawDesc)))
	})
	return file_dydxprotocol_accountplus_tx_proto_rawDescData
}

var file_dydxprotocol_accountplus_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dydxprotocol_accountplus_tx_proto_goTypes = []any{
	(*TxExtension)(nil), // 0: dydxprotocol.accountplus.TxExtension
}
var file_dydxprotocol_accountplus_tx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dydxprotocol_accountplus_tx_proto_init() }
func file_dydxprotocol_accountplus_tx_proto_init() {
	if File_dydxprotocol_accountplus_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dydxprotocol_accountplus_tx_proto_rawDesc), len(file_dydxprotocol_accountplus_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dydxprotocol_accountplus_tx_proto_goTypes,
		DependencyIndexes: file_dydxprotocol_accountplus_tx_proto_depIdxs,
		MessageInfos:      file_dydxprotocol_accountplus_tx_proto_msgTypes,
	}.Build()
	File_dydxprotocol_accountplus_tx_proto = out.File
	file_dydxprotocol_accountplus_tx_proto_goTypes = nil
	file_dydxprotocol_accountplus_tx_proto_depIdxs = nil
}
