// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: dydxprotocol/clob/tx.proto

// Trimmed, wire-compatible subset of dydxprotocol/clob/tx.proto: the two
// messages godex submits.

package clob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgPlaceOrder places an order. Type URL: /dydxprotocol.clob.MsgPlaceOrder.
type MsgPlaceOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPlaceOrder) Reset() {
	*x = MsgPlaceOrder{}
	mi := &file_dydxprotocol_clob_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPlaceOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlaceOrder) ProtoMessage() {}

func (x *MsgPlaceOrder) ProtoReflect() protoreflect.Message {
	mi := &file_dydxprotocol_clob_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlaceOrder.ProtoReflect.Descriptor instead.
func (*MsgPlaceOrder) Descriptor() ([]byte, []int) {
	return file_dydxprotocol_clob_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPlaceOrder) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// MsgCancelOrder cancels an order. Type URL: /dydxprotocol.clob.MsgCancelOrder.
type MsgCancelOrder struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	OrderId *OrderId               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Types that are valid to be assigned to GoodTilOneof:
	//
	//	*MsgCancelOrder_GoodTilBlock
	//	*MsgCancelOrder_GoodTilBlockTime
	GoodTilOneof  isMsgCancelOrder_GoodTilOneof `protobuf_oneof:"good_til_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCancelOrder) Reset() {
	*x = MsgCancelOrder{}
	mi := &file_dydxprotocol_clob_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCancelOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCancelOrder) ProtoMessage() {}

func (x *MsgCancelOrder) ProtoReflect() protoreflect.Message {
	mi := &file_dydxprotocol_clob_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCancelOrder.ProtoReflect.Descriptor instead.
func (*MsgCancelOrder) Descriptor() ([]byte, []int) {
	return file_dydxprotocol_clob_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCancelOrder) GetOrderId() *OrderId {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *MsgCancelOrder) GetGoodTilOneof() isMsgCancelOrder_GoodTilOneof {
	if x != nil {
		return x.GoodTilOneof
	}
	return nil
}

func (x *MsgCancelOrder) GetGoodTilBlock() uint32 {
	if x != nil {
		if x, ok := x.GoodTilOneof.(*MsgCancelOrder_GoodTilBlock); ok {
			return x.GoodTilBlock
		}
	}
	return 0
}

func (x *MsgCancelOrder) GetGoodTilBlockTime() uint32 {
	if x != nil {
		if x, ok := x.GoodTilOneof.(*MsgCancelOrder_GoodTilBlockTime); ok {
			return x.GoodTilBlockTime
		}
	}
	return 0
}

type isMsgCancelOrder_GoodTilOneof interface {
	isMsgCancelOrder_GoodTilOneof()
}

type MsgCancelOrder_GoodTilBlock struct {
	// good_til_block applies to short-term orders.
	GoodTilBlock uint32 `protobuf:"varint,2,opt,name=good_til_block,json=goodTilBlock,proto3,oneof"`
}

type MsgCancelOrder_GoodTilBlockTime struct {
	// good_til_block_time applies to stateful orders (unix seconds).
	GoodTilBlockTime uint32 `protobuf:"fixed32,3,opt,name=good_til_block_time,json=goodTilBlockTime,proto3,oneof"`
}

func (*MsgCancelOrder_GoodTilBlock) isMsgCancelOrder_GoodTilOneof() {}

func (*MsgCancelOrder_GoodTilBlockTime) isMsgCancelOrder_GoodTilOneof() {}

var File_dydxprotocol_clob_tx_proto protoreflect.FileDescriptor

var file_dydxprotocol_clob_tx_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63,
	0x6c, 0x6f, 0x62, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x64, 0x79,
	0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x6f, 0x62, 0x1a,
	0x1d, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6c,
	0x6f, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f,
	0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x2e, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c,
	0x6f, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0xb2, 0x01, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x35, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x63, 0x6c, 0x6f, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x6f, 0x6f,
	0x64, 0x5f, 0x74, 0x69, 0x6c, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x6f, 0x6f, 0x64, 0x54, 0x69, 0x6c, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x2f, 0x0a, 0x13, 0x67, 0x6f, 0x6f, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x5f, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x48, 0x00,
	0x52, 0x10, 0x67, 0x6f, 0x6f, 0x64, 0x54, 0x69, 0x6c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x67, 0x6f, 0x6f, 0x64, 0x5f, 0x74, 0x69, 0x6c, 0x5f, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x44, 0x61, 0x69, 0x73, 0x75, 0x6b, 0x65, 0x59, 0x6f, 0x64, 0x61, 0x2f, 0x67,
	0x6f, 0x64, 0x65, 0x78, 0x2f, 0x64, 0x79, 0x64, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x79, 0x64, 0x78, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x63, 0x6c, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_dydxprotocol_clob_tx_proto_rawDescOnce sync.Once
	file_dydxprotocol_clob_tx_proto_rawDescData []byte
)

func file_dydxprotocol_clob_tx_proto_rawDescGZIP() []byte {
	file_dydxprotocol_clob_tx_proto_rawDescOnce.Do(func() {
		file_dydxprotocol_clob_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dydxprotocol_clob_tx_proto_rawDesc), len(file_dydxprotocol_clob_tx_proto_rawDesc)))
	})
	return file_dydxprotocol_clob_tx_proto_rawDescData
}

var file_dydxprotocol_clob_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dydxprotocol_clob_tx_proto_goTypes = []any{
	(*MsgPlaceOrder)(nil),  // 0: dydxprotocol.clob.MsgPlaceOrder
	(*MsgCancelOrder)(nil), // 1: dydxprotocol.clob.MsgCancelOrder
	(*Order)(nil),          // 2: dydxprotocol.clob.Order
	(*OrderId)(nil),        // 3: dydxprotocol.clob.OrderId
}
var file_dydxprotocol_clob_tx_proto_depIdxs = []int32{
	2, // 0: dydxprotocol.clob.MsgPlaceOrder.order:type_name -> dydxprotocol.clob.Order
	3, // 1: dydxprotocol.clob.MsgCancelOrder.order_id:type_name -> dydxprotocol.clob.OrderId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dydxprotocol_clob_tx_proto_init() }
func file_dydxprotocol_clob_tx_proto_init() {
	if File_dydxprotocol_clob_tx_proto != nil {
		return
	}
	file_dydxprotocol_clob_order_proto_init()
	file_dydxprotocol_clob_tx_proto_msgTypes[1].OneofWrappers = []any{
		(*MsgCancelOrder_GoodTilBlock)(nil),
		(*MsgCancelOrder_GoodTilBlockTime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dydxprotocol_clob_tx_proto_rawDesc), len(file_dydxprotocol_clob_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dydxprotocol_clob_tx_proto_goTypes,
		DependencyIndexes: file_dydxprotocol_clob_tx_proto_depIdxs,
		MessageInfos:      file_dydxprotocol_clob_tx_proto_msgTypes,
	}.Build()
	File_dydxprotocol_clob_tx_proto = out.File
	file_dydxprotocol_clob_tx_proto_goTypes = nil
	file_dydxprotocol_clob_tx_proto_depIdxs = nil
}
